# Generated by Django 5.1.7 on 2025-06-02 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="state_date",
            new_name="start_date",
        ),
    ]
